CLASS_INDEX = "geoqa-class"
ENTITY_INDEX = "geoqa-entity"
RELATION_INDEX = "geoqa-relation"
LABEL_PRED_LOWER = "http://www.w3.org/2000/01/rdf-schema#label"
SPARQL_ENDPOINT = "http://geo-qa.cs.upb.de:3030/bremen_geo/sparql"
